config/routes.rb
Gentoo::Application.routes.draw do
  get "/help" => "help#index"
  resources :reviews
  resources :candidates do
    member do
      put :sponsor
      put :recruit
      get :ssh_key
      get :gpg_key
    end
    collection do
      get :ready
    end
    resources :answers do
      collection do
        get :export
      end
    end
  end

  resources :groups do
    resources :questions
    member do
      put :subscribe
      delete :unsubscribe
    end
  end

  resources :questions do
    collection do
      get :answered
      get :unanswered
      get :assigned
    end
    resources :answers
    resources :comments
  end

  resources :answers do
    resources :comments
    collection do
      get :review
    end
    member do
      put :accept
      put :reject
    end
  end

  resources :sponsees

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'home#index'

end

app/views/shared/_breadcrumbs.html.haml
- if @breadcrumbs.present?
  %ul.breadcrumb
    - separator = divider
    - @breadcrumbs[0..-2].each do |crumb|
      %li
        = link_to crumb[:name], crumb[:url], crumb[:options]
        %span.divider= separator
    %li.active
      = @breadcrumbs.last[:name]

app/views/shared/_sidebar.html.haml
- if user_signed_in?
  .panel.panel-primary
    - if current_user.candidate?
      .panel-heading
        .panel-title Welcome
      .panel-body
        %ul.nav.nav-list
          %li.nav-header Questions
          %li= link_to "To be answered", unanswered_questions_path
          %li= link_to "Already answered", answered_questions_path
          %li= link_to "All", assigned_questions_path
      .panel-footer= progress_bar(current_user.progress)
    - elsif current_user.mentor?
      .panel-heading
        .panel-title Mentor
      .panel-body
        %ul.nav.nav-list
          %li.nav-header Actions
          %li= link_to "Answers to review", review_answers_path
          %li= link_to "All reviewed answers", reviews_path
          %li= link_to "Sponsees", sponsees_path
          %li= link_to "Candidates", candidates_path

    - elsif current_user.admin? || current_user.recruiter?
      .panel-heading
        .panel-title Recruiter actions
      .panel-body
        %ul.nav.nav-list
          %li= link_to "Admin Dashboard", admin_dashboard_path if current_user.admin?
          %li= link_to "Candidates", candidates_path
          %li= link_to "Sponsees", sponsees_path
          %li= link_to "Answers to review", review_answers_path
          %li= link_to "All reviewed answers", reviews_path
          %li= link_to "Ready Candidates", ready_candidates_path
          %li= link_to "Submit questions", new_question_path