config/routes.rb
Gentoo::Application.routes.draw do
  get "/help" => "help#index"
  resources :reviews
  resources :candidates do
    member do
      put :sponsor
      put :recruit
      get :ssh_key
      get :gpg_key
    end
    collection do
      get :ready
    end
    resources :answers do
      collection do
        get :export
      end
    end
  end

  resources :groups do
    resources :questions
    member do
      put :subscribe
      delete :unsubscribe
    end
  end

  resources :questions do
    collection do
      get :answered
      get :unanswered
      get :assigned
    end
    resources :answers
    resources :comments
  end

  resources :answers do
    resources :comments
    collection do
      get :review
    end
    member do
      put :accept
      put :reject
    end
  end

  resources :sponsees

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Workflow
  acts_as_commentable
  acts_as_paranoid

  attr_accessible :content, :question_id, :user_id, :user, :operator

  belongs_to :user
  belongs_to :question
  belongs_to :operator, class_name: "User"

  validates_presence_of :user, :question, :content

  default_scope -> { order("updated_at DESC") }

  scope :for, -> user, question {
    where(question_id: question.id).where(user_id: user.id)
  }

  scope :awaiting_review, -> { where(workflow_state: "awaiting_review") }
  scope :reviewable, -> user {
    joins(:user).where("users.id" => user.sponsees.map(&:id))
  }

  scope :reviewed, -> { where.not(workflow_state: "awaiting_review") }

  scope :accepted, -> { where(workflow_state: "accepted") }

  scope :rejected_answers, -> user {
    where(user_id: user.id).where(workflow_state: 'rejected')
  }

  workflow do
    state :awaiting_review do
      event :accept, transitions_to: :accepted
      event :reject, transitions_to: :rejected
    end

    state :rejected do
      event :accept, transitions_to: :accepted
      event :submit, transitions_to: :awaiting_review
    end
    state :accepted do
      event :reject, transitions_to: :rejected
    end
  end

  def state
    current_state.to_s.humanize
  end

  def mentor_action!(user)
    update_attribute(:operator, user)
  end

  def next
    self.class.where(user_id: user_id).where("id > ?", id).limit(1).first
  end

  def previous
    self.class.unscoped.where(user_id: user_id).order("id DESC").where("id < ?", id).limit(1).first
  end

end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource

  before_filter :get_question, only: [:new, :edit, :update, :create] 
  def index
    authorize! :review, Answer
    @candidate = User.find_by name: params[:candidate_id] 
    if @candidate.candidate?
      @answers = @candidate.answers.page params[:page]
    else
      flash[:alert] = "This is not a candidate."
      redirect_to root_url
    end
  end

  def new
    authorize! :answer, Question
    @answer = current_user.answer_for(@question)
    if @answer
      render :edit
    else
      @answer = @question.answers.build(user: current_user)
    end
  end

  def create
    authorize! :answer, Question
    if @answer = @question.answers.where(user_id: current_user.id).first
      flash[:notice] = "You have already created an answer for this question!"
      redirect_to [@question, @answer]
    else
      @answer = @question.answers.new(params[:answer])
      @answer.user = current_user
      if @answer.save
        AnswerNotification.update(current_user, @answer).deliver
        redirect_to [@question, @answer]
      else
        render :new
      end
    end
  end

  def update
    @answer = @question.answers.find params[:id]
    @answer.update_attributes(params[:answer])
    @answer.submit! if @answer.rejected?
    AnswerNotification.update(current_user, @answer).deliver
    redirect_to [@question, @answer]
  end

  def edit
    @answer = @question.answers.find params[:id]
    if current_user.candidate? && @answer.user != current_user
      flash[:alert] = "You cannot edit this answer."
      redirect_to @question
    end
  end

  def show
    @answer = Answer.find params[:id]
    @question = @answer.question
    if current_user.candidate? && @answer.user != current_user
      flash[:alert] = "You cannot view this answer."
      redirect_to @question
    end
    if current_user.mentor? || current_user.recruiter?
      rejected_answers = Answer.rejected_answers(@answer.user)
      if rejected_answers.length > 1 && rejected_answers.include?(@answer)
        index = rejected_answers.find_index(@answer)
        @next_rejected = rejected_answers.rotate(index + 1).first
      end
    end
  end

  def review
    @answers = current_user.answers_waiting_review.page params[:page]
  end

  def accept
    authorize! :review, Answer
    @answer = Answer.find params[:id]
    current_user.accept!(@answer)
    AnswerNotification.accept(current_user, @answer.user, @answer).deliver
    check_user_ready(@answer.user, @answer.question.group)
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def reject
    authorize! :review, Answer
    @answer = Answer.find params[:id]
    current_user.reject!(@answer)
    AnswerNotification.reject(current_user, @answer.user, @answer).deliver
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def export
    authorize! :review, Answer
    @candidate = User.find_by name: params[:candidate_id] 
    if @candidate.candidate?
      send_data @candidate.export_answers, filename: "#{@candidate.name}.csv", type: 'text/csv; charset=iso-8859-1; header=present'
    else
      flash[:alert] = "This is not a candidate."
      redirect_to root_url
    end

  end

  private
  def check_user_ready(user, group)
    if user.ready_for?(group)
      user.get_ready!(group)
      Notification.ready(user, group).deliver
    end
  end

  def get_question
    @question = Question.find(params[:question_id])
  end
end

app/views/answers/_form.html.haml
.page-header
  %h3= @question.title
.page-header
  %p= markdown(@question.content)
#epiceditor
= simple_form_for [@question, @answer], :html => { :class => 'form-horizontal' } do |f|
  = f.input :user_id, as: :hidden
  = f.input :question_id, as: :hidden
  = f.input :content, as: :hidden
  .btn-group
    = f.button :submit, :class => 'btn-primary', value: "Submit"
    = link_to t('.cancel', :default => t("helpers.links.cancel")), [@question.group, :questions], :class => 'btn btn-default'
    = render :partial => 'nav_buttons'
- content_for :js do
  :javascript
    $(function() {
      var epicEditor = new EpicEditor({basePath: ""}).load().reflow('height');
      epicEditor.importFile("answer", "#{escape_javascript(@answer.content)}")
      $("form").submit(function() {
        $("#answer_content").val(epicEditor.exportFile());
      })
    });

app/views/answers/_list.html.haml
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Question
        %th By
        %th
    %tbody
      - @answers.each do |answer|
        %tr
          %td= answer.question.title
          %td= unsluggish_name answer.user.name
          %td
            - if answer.awaiting_review?
              = link_to [answer.question, answer], class: 'btn btn-warning' do
                %i.fa.fa-group
                Review
            - else
              = answer_status(answer)
              = link_to "View", [answer.question, answer], class: "btn"
  = paginate @answers

app/views/answers/_nav_buttons.html.haml
.btn-group
  - if can? :answer, Question
    - if previous_question = @question.previous
      = link_to [:new, previous_question, :answer], class: "btn btn-default" do
        %i.fa.fa-step-backward
        Previous
    = link_to [@question.group, :questions], class: "btn btn-default" do
      %i.fa.fa-eject
      All
    - if next_question = @question.next
      = link_to [:new, next_question, :answer], class: "btn btn-default" do
        Next
        %i.fa.fa-step-forward
  - elsif @answer
    - if previous_answer = @answer.previous
      = link_to [@question, previous_answer], class: "btn btn-default" do
        %i.fa.fa-step-backward
        Previous
    = link_to [:review, :answers], class: "btn btn-default" do
      %i.fa.fa-eject
      All
    - if next_answer = @answer.next
      = link_to [@question, next_answer], class: "btn btn-default" do
        Next
        %i.fa.fa-step-forward
    - if next_rejected_answer = @next_rejected
      = link_to [@question, next_rejected_answer], class: "btn btn-default" do
        Next Rejected
        %i.fa.fa-circle-arrow-right

app/views/answers/accept.js.haml
$("a[data-remote=true]").parent(".btn-group").fadeOut();
$(".label-info").removeClass("label-info").addClass("label-success").html("Accepted by #{unsluggish_name(current_user.name)}");
$(".label-danger").removeClass("label-danger").addClass("label-success").html("Accepted by #{unsluggish_name(current_user.name)}");

app/views/answers/edit.html.haml
= render :partial => "form"

app/views/answers/index.html.haml
.page-header
  %h2 Answers by #{@candidate.name}
  %p= link_to "Export csv", export_candidate_answers_path(@candidate, format: :csv)
- if @answers.empty?
  %p Empty list.
- else
  = render :partial => 'list'

app/views/answers/new.html.haml
= render :partial => "form"

app/views/answers/reject.js.haml
$("a[data-remote=true]").parent(".btn-group").fadeOut();
$(".label-info").removeClass("label-info").addClass("label-danger").html("Rejected by #{current_user.name}");
$(".label-success").removeClass("label-success").addClass("label-danger").html("Rejected by #{current_user.name}");

app/views/answers/review.html.haml
.page-header
  %h2 Answers to review
- if @answers.empty?
  %p Nothing to review.
- else
  = render :partial => 'list'

app/views/answers/show.html.haml
.page-header
  %h3= @question.title

%p.lead.question= markdown(@question.content)

%p
  = answer_status(@answer)
  answer
  = link_to "by #{unsluggish_name(@answer.user.name)}", candidate_path(@answer.user)
.well= markdown @answer.content
- if can? :review, Answer
  .btn-group
    - if @answer.awaiting_review? || @answer.rejected?
      = link_to [:accept, @answer], class: 'btn btn-primary', method: :put, remote: true do
        %i.fa.fa-ok
        Accept
    - if @answer.awaiting_review? || @answer.accepted?
      = link_to [:reject, @answer], method: :put, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger', remote: true do
        %i.fa.fa-remove
        Reject
= render :partial => 'nav_buttons'
%p= render :partial => 'comments/form', locals: {commentable: @answer}