config/routes.rb
Gentoo::Application.routes.draw do
  get "/help" => "help#index"
  resources :reviews
  resources :candidates do
    member do
      put :sponsor
      put :recruit
      get :ssh_key
      get :gpg_key
    end
    collection do
      get :ready
    end
    resources :answers do
      collection do
        get :export
      end
    end
  end

  resources :groups do
    resources :questions
    member do
      put :subscribe
      delete :unsubscribe
    end
  end

  resources :questions do
    collection do
      get :answered
      get :unanswered
      get :assigned
    end
    resources :answers
    resources :comments
  end

  resources :answers do
    resources :comments
    collection do
      get :review
    end
    member do
      put :accept
      put :reject
    end
  end

  resources :sponsees

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'home#index'

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :sponsor, User
    @candidates = User.candidates.page params[:page]
  end

  def show
    authorize! :sponsor, User
    @candidate = User.find_by name: params[:id]
  end

  def sponsor
    authorize! :sponsor, User
    @novice = User.find_by name: params[:id]
    current_user.recruit(@novice)
    redirect_to action: :index
  end

  def ready
    authorize! :promote, User
    @candidates = User.ready.page params[:page]
  end

  def developers
    @developers = ReadyUser.developers.page(params[:page]).map(&:user)
  end

  def arch_testers
    @testers = ReadyUser.arch_testers.page(params[:page]).map(&:user)
  end

  def staffers
    @staffers = ReadyUser.staffers.page(params[:page]).map(&:user)
  end

  # This is actually promote to mentor
  def recruit
    authorize! :promote, User
    @novice = User.find_by name: params[:id]
    # XXX The recruiter choose what post to assign the candidate
    # @novice.recuite! # => staffer
    @novice.promote! # => mentor
    @mentors = @novice.mentors
    @mentors.each{|mentor| @novice.mentors.delete(mentor)}
    # XXX only the one with the right group
    @novice.ready_users.delete_all
    @novice.save
    Notification.accept(current_user, @novice).deliver
    Notification.recruit(current_user, @novice, @mentors).deliver
    flash[:notice] = "#{@novice.name} is now a gentoo developer."
    redirect_to action: :ready
  end

  def ssh_key
    authorize! :sponsor, User
    @candidate = User.find_by name: params[:id]
    send_data @candidate.ssh_key, filename: "#{@candidate.name}-ssh.pub"
  end

  def gpg_key
    authorize! :sponsor, User
    @candidate = User.find_by name: params[:id]
    send_data @candidate.gpg_key, filename: "#{@candidate.name}-gpg.pub"
  end
end

app/views/candidates/_list.html.haml
- list.to_a.in_groups_of(2, false) do |sponsees|
  .row
    - sponsees.each do |sponsee|
      .col-md-6.col-sm-6.col-xs-12
        .panel.panel-default
          .panel-body
            .media
              = link_to candidate_path(sponsee), class: "pull-left" do
                = gravatar_tag(sponsee, html: {class: "media-object"})
              .media-body
                %h3.media-heading
                  = link_to unsluggish_name(sponsee.name), candidate_path(sponsee)
                  %span.badge(title='Number of mentors')= sponsee.mentors.count
                %p= truncate(sponsee.biography, length: 150)
          .panel-footer
            .btn-group
              - if can?(:sponsor, User)
                - if current_user.mentoring?(sponsee)
                  = link_to sponsee_path(sponsee), method: :delete, class: "btn btn-primary" do
                    %i.fa.fa-unlock
                    Unrecruit
                  - unless sponsee.ready?
                    = link_to candidate_answers_path(sponsee), class: "btn btn-warning" do
                      %i.fa.fa-group
                      Review
                - else
                  = link_to sponsor_candidate_path(sponsee), method: :put, class: "btn btn-primary" do
                    %i.fa.fa-umbrella
                    Recruit
                - if (current_user.recruiter? || current_user.admin?) && !current_user.mentoring?(sponsee)
                  = link_to candidate_answers_path(sponsee), class: "btn btn-success" do
                    %i.fa.fa-check
                    Grade
              - if can?(:promote, User) && sponsee.ready?
                = link_to recruit_candidate_path(sponsee), method: :put, class: "btn btn-danger" do
                  %i.fa.fa-trophy
                  Promote
  = paginate list

app/views/candidates/index.html.haml
.page-header
  %h2 Newbees list
- if @candidates.empty?
  %p Lambs were slaughtered.
= render partial: 'list', object: @candidates

app/views/candidates/ready.html.haml
.page-header
  %h2 Candidates
- if @candidates.empty?
  %p All candidates were promoted.
  
= render :partial => 'list', object: @candidates

app/views/candidates/show.html.haml
:css
  strong {
    display: inline-block;
    text-align: right;
    width: 200px;
  }
.panel.panel-info
  .panel-heading
    .panel-title= unsluggish_name @candidate.name
  .panel-body
    .row
      .col-md-9
        %p 
          %strong Email
          = @candidate.email
        %p
          %strong Date of birth
          = @candidate.date_of_birth
        %p 
          %strong SSH public key
          - unless @candidate.ssh_key.blank?
            = link_to "download", ssh_key_candidate_path(@candidate)
          - else
            To be uploaded
        %p 
          %strong GnuPG public key
          - unless @candidate.gpg_key.blank?
            = link_to "download", gpg_key_candidate_path(@candidate)
          - else
            To be uploaded

        %p 
          %strong Address
          = @candidate.address
        %p
          %strong Skills
          = @candidate.skills
        %p 
          %strong Other experiences
          = @candidate.other_skills
        %p 
          %strong Contributed projects
          = @candidate.projects
        %p
          %strong Description
        %p= markdown @candidate.biography
      .col-md-3
        .thumbnail= gravatar_tag(@candidate)
        %p
          %em Subscribed quests
          - @candidate.groups.each do |group|
            %p
              = link_to group.name, candidate_answers_path(@candidate)
              %span.label.label-info= @candidate.progress_for(group)
          - if @candidate.groups.empty?
            %p No question group subscribed.

        %p
          %em Badges Earned
          - @candidate.badges.each do |badge|
            %span.label.label-info= badge
          - if @candidate.badges.empty?
            %span.label.label-default None Badges Earned

  .panel-footer= link_to "<<Back", :back